-- BUILD DATABASE SQLite
CREATE TABLE IF NOT EXISTS books(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	author TEXT
);

CREATE TABLE IF NOT EXISTS members(
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS rents(
	uuid TEXT PRIMARY KEY,
	id_book INTEGER,
	id_member TEXT,
	beginning DATETIME NOT NULL,
	ending DATETIME DEFAULT NULL,

	FOREIGN KEY(id_book) REFERENCES books(id),
	FOREIGN KEY(id_member) REFERENCES members(id)
);
